repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=88]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        args: [--max-line-length=88]
        files: "\\.py$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.0
    hooks:
      - id: eslint
        args: [--fix]
        files: "\\.(js|jsx|ts|tsx|mjs)$"